# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Poderia ter um pipeline para uma branch de teste
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Olá Fadultech!
  displayName: 'Mensagem de teste'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true